backend:
  name: git-gateway
  branch: main # Replace "main" with your branch name if it's different

media_folder: "images/uploads" # Where uploaded images will be stored
public_folder: "/images/uploads" # Public path to uploaded images

collections:
  - name: "blog" # The name of your collection
    label: "Blog Posts" # How it will appear in the CMS
    folder: "_posts" # Folder to store blog posts
    create: true # Allow new entries
    slug: "{{slug}}" # Generate URL-friendly names

    fields: # Fields for each blog post
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
